import React from 'react'
import Head from 'next/head'

// component
import Footer from './Footer'
import Header from './Header'
export default function Layout({ children, title, description }) {
  return (
    <>
      <Head>
        <title>{title || "Belajar next js"}</title>
        <meta name="description" content={description || "Generated by create next app"} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      <Footer />
    </>
  )
}
